"#version 330\n"
"layout(location = 0) in vec3 vertexPosition;\n"
"layout(location = 1) in vec2 vertexTexCoord;\n"
"layout(location = 3) in float vertexColor;\n"
"uniform mat4 mvp;\n"
"uniform mat4 matModelView;\n"
"out vec2 fragTexCoord;\n"
"out vec4 fragColor;\n"
"out float fogDistance;\n"
"out vec4 sunFragColor;\n"
"void main() {\n"
"    fragTexCoord = vertexTexCoord / 256.0;\n"
"    fragColor = vec4((int(vertexColor) >> 4) / 15.0, (int(vertexColor) >> 4) / 15.0, (int(vertexColor) >> 4) / 15.0, 1.0);\n"
"    sunFragColor = vec4((int(vertexColor) & 15) / 15.0, (int(vertexColor) & 15) / 15.0, (int(vertexColor) & 15) / 15.0, 1.0);\n"
"    vec3 pos = vec3(vertexPosition.x / 15.0, vertexPosition.y / 15.0, vertexPosition.z / 15.0);\n"
"    fogDistance = length((matModelView * vec4(pos, 1.0)).xyz);\n"
"    gl_Position = mvp * vec4(pos, 1.0);\n"
"}\n"
