"#version 330\n"
"in vec2 fragTexCoord;\n"
"in vec4 fragColor;\n"
"in float fogDistance;\n"
"in vec4 sunFragColor;\n"
"uniform sampler2D texture0;\n"
"uniform float sunlightStrength;\n"
"uniform vec3 fogColor;\n"
"uniform float fogStart;\n"
"uniform float fogEnd;\n"
"out vec4 finalColor;\n"
"void main() {\n"
"   vec4 texelColor = texture(texture0, fragTexCoord);\n"
"   if(texelColor.a == 0.0) discard;\n"
"   /* Ambient fill from cosmic glow — keeps shadowed blocks visible\n"
"    * with a faint violet-blue cast instead of pure black. */\n"
"   vec3 ambient = vec3(0.08, 0.06, 0.14);\n"
"   vec4 litColor = texelColor * clamp(sunFragColor * sunlightStrength + fragColor + vec4(ambient, 0), vec4(0.12, 0.10, 0.16, 1), vec4(1,1,1,1));\n"
"   /* Slight rim glow: boost saturation at fog boundary for a magical\n"
"    * halo effect around distant islands. */\n"
"   float fogAmount = smoothstep(fogStart, fogEnd, fogDistance);\n"
"   vec3 rimmed = litColor.rgb + vec3(0.02, 0.01, 0.04) * fogAmount;\n"
"   finalColor = vec4(mix(rimmed, fogColor, fogAmount), litColor.a);\n"
"}\n"
