"#version 100\n"
"precision mediump float;\n"
"varying vec2 fragTexCoord;\n"
"varying vec4 fragColor;\n"
"varying mediump float fogDistance;\n"
"varying vec4 sunFragColor;\n"
"uniform sampler2D texture0;\n"
"uniform float sunlightStrength;\n"
"uniform vec3 fogColor;\n"
"uniform float fogStart;\n"
"uniform float fogEnd;\n"
"void main() {\n"
"   vec4 texelColor = texture2D(texture0, fragTexCoord);\n"
"   if(texelColor.a == 0.0) discard;\n"
"   vec3 ambient = vec3(0.08, 0.06, 0.14);\n"
"   vec4 litColor = texelColor * clamp(sunFragColor * sunlightStrength + fragColor + vec4(ambient, 0), vec4(0.12, 0.10, 0.16, 1), vec4(1,1,1,1));\n"
"   float fogAmount = smoothstep(fogStart, fogEnd, fogDistance);\n"
"   vec3 rimmed = litColor.rgb + vec3(0.02, 0.01, 0.04) * fogAmount;\n"
"   gl_FragColor = vec4(mix(rimmed, fogColor, fogAmount), litColor.a);\n"
"}\n"
