"#version 330\n"
"layout(location = 0) in vec3 vertexPosition;"
"layout(location = 3) in vec4 vertexColor;"
"layout(location = 1) in vec2 vertexTexCoord;"
"uniform mat4 mvp;"
"uniform mat4 matModel;"
"uniform vec3 cameraPosition;"
"out vec4 fragColor;"
"out vec2 fragTexCoord;"
"out float fogDistance;"
"void main() {"
"    vec3 worldPosition = (matModel * vec4(vertexPosition, 1.0)).xyz;"
"    fogDistance = length(worldPosition.xz - cameraPosition.xz);"
"    fragColor = vertexColor;"
"    fragTexCoord = vertexTexCoord;"
"    gl_Position = mvp * vec4(vertexPosition, 1.0);"
"}"
