"#version 330\n"
"in vec4 fragColor;"
"in float fogDistance;"
"in vec2 fragTexCoord;"
"uniform sampler2D texture0;"
"uniform vec4 colDiffuse;"
"uniform vec3 fogColor;"
"uniform float fogStart;"
"uniform float fogEnd;"
"out vec4 finalColor;"
"void main() {"
"    vec3 sampled = texture(texture0, fragTexCoord).rgb;"
"    vec3 rockColor = sampled * fragColor.rgb * colDiffuse.rgb * vec3(1.05, 0.88, 1.18);"
"    float fogAmount = smoothstep(fogStart, fogEnd, fogDistance);"
"    finalColor = vec4(mix(rockColor, fogColor, fogAmount), 1.0);"
"}"
