"#version 100\n"
"precision mediump float;\n"
"varying vec4 fragColor;\n"
"varying mediump float fogDistance;\n"
"uniform vec4 colDiffuse;\n"
"uniform vec3 fogColor;\n"
"uniform float fogStart;\n"
"uniform float fogEnd;\n"
"void main() {\n"
"    vec3 rockColor = fragColor.rgb * colDiffuse.rgb;\n"
"    float sparkle = fract(sin(dot(fragColor.rg, vec2(12.9898, 78.233))) * 43758.5453);\n"
"    rockColor += vec3(0.04, 0.02, 0.06) * step(0.92, sparkle);\n"
"    float fogAmount = smoothstep(fogStart, fogEnd, fogDistance);\n"
"    gl_FragColor = vec4(mix(rockColor, fogColor, fogAmount), 1.0);\n"
"}\n"
