"#version 330\n"
"in vec4 fragColor;\n"
"in float fogDistance;\n"
"uniform vec4 colDiffuse;\n"
"uniform vec3 fogColor;\n"
"uniform float fogStart;\n"
"uniform float fogEnd;\n"
"out vec4 finalColor;\n"
"void main() {\n"
"    vec3 rockColor = fragColor.rgb * colDiffuse.rgb;\n"
"    /* Faint sparkle: modulate by a pseudo-random based on fragment\n"
"    * position to simulate crystal glints on asteroid surfaces. */\n"
"    float sparkle = fract(sin(dot(fragColor.rg, vec2(12.9898, 78.233))) * 43758.5453);\n"
"    rockColor += vec3(0.04, 0.02, 0.06) * step(0.92, sparkle);\n"
"    float fogAmount = smoothstep(fogStart, fogEnd, fogDistance);\n"
"    finalColor = vec4(mix(rockColor, fogColor, fogAmount), 1.0);\n"
"}\n"
