// Scans terrain generated by the *user's* worldgenerator.c (from Midless-src.rar)
// and reports "water walls": water cells with dry air as a horizontal neighbour.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "raylib.h"
#include "raymath.h"
#include "chunk/chunk.h"
#include "worldgenerator.h"

#define R 10            // chunk radius scanned around origin (XZ)
#define CY0 0
#define CY1 5           // chunk Y range 0..5 -> blocks 0..95
#define NX ((2*R+1)*16)
#define NY ((CY1-CY0+1)*16)

static unsigned short *world; // [y][z][x]
static inline unsigned short *at(int x, int y, int z) { return &world[((size_t)y*NX + z)*NX + x]; }

int main(int argc, char **argv) {
    int seed = argc > 1 ? atoi(argv[1]) : 1234;
    int useStructures = argc > 2 ? atoi(argv[2]) : 1;
    ServerWorldGenerator_Init(seed);
    world = calloc((size_t)NX*NX*NY, sizeof *world);
    Chunk *c = MemAlloc(sizeof *c);
    for (int cy = CY0; cy <= CY1; cy++) for (int cz = -R; cz <= R; cz++) for (int cx = -R; cx <= R; cx++) {
        memset(c, 0, sizeof *c);
        c->position = (Vector3){cx, cy, cz};
        c->blockPosition = Vector3Multiply(c->position, CHUNK_SIZE_VEC3);
        ServerWorldGenerator_Generate(c);
        if (useStructures) ServerWorldGenerator_GenerateStructures(c);
        for (int i = 0; i < CHUNK_SIZE; i++) {
            Vector3 lp = ServerChunk_IndexToPos(i);
            *at((cx+R)*16 + (int)lp.x, (cy-CY0)*16 + (int)lp.y, (cz+R)*16 + (int)lp.z) = c->data[i];
        }
    }
    long water = 0, walls = 0, dryBelowSea = 0, dryBelowSeaOpenSky = 0, floating = 0;
    int minWallY = 999, maxWallY = -1;
    long wallsPerY[NY] = {0};
    static const int d4[4][2] = {{1,0},{-1,0},{0,1},{0,-1}};
    // open-to-sky map: column has only air/plants above y (approx: everything above is 0/12/13/22)
    for (int y = 1; y < NY-1; y++) for (int z = 1; z < NX-1; z++) for (int x = 1; x < NX-1; x++) {
        int id = *at(x,y,z);
        if (id == 5 || id == 20) {
            water++;
            bool wall = false;
            for (int k = 0; k < 4; k++) if (*at(x+d4[k][0], y, z+d4[k][1]) == 0) wall = true;
            if (wall) { walls++; wallsPerY[y]++; if (y < minWallY) minWallY = y; if (y > maxWallY) maxWallY = y; }
            if (*at(x, y-1, z) == 0) floating++;
        } else if (id == 0 && y < 48) {
            dryBelowSea++;
            // is this dry cell open to the sky? (nothing but air straight up)
            bool open = true;
            for (int yy = y+1; yy < NY; yy++) { int a = *at(x,yy,z); if (a != 0 && a != 12 && a != 13 && a != 22) { open = false; break; } }
            if (open) dryBelowSeaOpenSky++;
        }
    }
    printf("seed %d structures=%d: area %dx%d blocks, y 0..%d\n", seed, useStructures, NX, NX, NY-1);
    printf("  water cells            : %ld\n", water);
    printf("  water next to dry air  : %ld  (y range %d..%d)\n", walls, minWallY, maxWallY);
    printf("  water above air        : %ld\n", floating);
    printf("  dry air below y=48     : %ld  (of which open to sky: %ld)\n", dryBelowSea, dryBelowSeaOpenSky);
    printf("  walls per y (y: count) :");
    for (int y = 0; y < NY; y++) if (wallsPerY[y]) printf(" %d:%ld", y, wallsPerY[y]);
    printf("\n");
    // Print one example wall with a small cross-section (X along, fixed Z) for eyeballing
    for (int y = 40; y < 48 && walls; y++) for (int z = 1; z < NX-1; z++) for (int x = 1; x < NX-1; x++) {
        if (*at(x,y,z) != 5) continue;
        if (*at(x+1,y,z) != 0) continue;
        printf("  example: water at world (%d,%d,%d), dry air at x+1. Cross-section z=%d, x=%d..%d, y=52 down to 36:\n",
               x-R*16, y, z-R*16, z-R*16, x-8-R*16, x+12-R*16);
        for (int yy = 52; yy >= 36; yy--) {
            printf("    y=%2d ", yy);
            for (int xx = x-8; xx <= x+12; xx++) { int id = *at(xx,yy,z); putchar(id==0?'.':id==5?'~':id==6?'s':id==1?'#':id==3?'g':id==2?'d':id==20?'i':id==21?'S':'o'); }
            printf("\n");
        }
        goto done;
    }
done:
    return 0;
}
