#!/usr/bin/env python3
"""Cell-by-cell comparison: chunk generated by the exe under Unicorn (emu.py) vs the same chunk
from a native Linux build of worldgenerator.c (../dumpchunk.c). Proves the binary patch is
semantically identical to the C patch.

usage: compare_native.py <exe> <dumpchunk-binary> <seed> <cx> <cy> <cz>
"""
import collections, os, subprocess, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import emu
path, native, seed = sys.argv[1], sys.argv[2], int(sys.argv[3]); cx, cy, cz = map(int, sys.argv[4:7])
m = emu.Machine(path); m.init(seed); e = m.chunk(cx, cy, cz)
n = subprocess.run([native, str(seed), str(cx), str(cy), str(cz), '1'], capture_output=True, check=True).stdout
ev = [e[2 * i] | (e[2 * i + 1] << 8) for i in range(4096)]; nv = [n[2 * i] | (n[2 * i + 1] << 8) for i in range(4096)]
diff = [(nv[i], ev[i]) for i in range(4096) if nv[i] != ev[i]]
print(f'{os.path.basename(path)} vs {os.path.basename(native)}: chunk ({cx},{cy},{cz}) seed {seed}: '
      f'identical={not diff} diffs={len(diff)} water={ev.count(5)} {collections.Counter(diff).most_common(4)}')
sys.exit(0 if not diff else 1)
